version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432"
    ports:
      - 8888:8080
    networks:
      - til_actix
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 5432:5432
    networks:
      - til_actix
    volumes:
      - "til_actix:/var/lib/postgresql/data"
  adminer:
    image: adminer
    ports:
    - 9000:8080
    networks:
      - til_actix
    depends_on:
      - db

networks:
  til_actix:

volumes:
  til_actix:
